title: GISmedes
remote_theme: "just-the-docs/just-the-docs"

# Set a path/url to a logo that will be displayed instead of the title
logo: "https://github.com/megsmedes/GISmedes/blob/main/img/Portrait_2024.jpg"
